// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function sanitizeSupabaseUrl(rawUrl?: string): string {
  const url = (rawUrl || "https://jgurginsphlfdzwkitso.supabase.co").trim();
  return url
    .replace(/\/+$/, "")
    .replace(/\/(rest|auth|storage)(\/v\d+)?$/i, "")
    .replace(/\/v\d+$/i, "");
}

function createSupabaseAdminClient() {
  const rawUrl = process.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_URL = sanitizeSupabaseUrl(rawUrl);
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    console.warn(`[Supabase] Missing SUPABASE_SERVICE_ROLE_KEY for admin client.`);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY || '', {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
