// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function sanitizeSupabaseUrl(rawUrl?: string): string {
  const url = (rawUrl || "https://jgurginsphlfdzwkitso.supabase.co").trim();
  return url
    .replace(/\/+$/, "")
    .replace(/\/(rest|auth|storage)(\/v\d+)?$/i, "")
    .replace(/\/v\d+$/i, "");
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const rawUrl =
    (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env['VITE_SUPABASE_URL']) ||
    process.env['VITE_SUPABASE_URL'] ||
    process.env['SUPABASE_URL'];

  const SUPABASE_URL = sanitizeSupabaseUrl(rawUrl);

  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY']) ||
    process.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    process.env['SUPABASE_PUBLISHABLE_KEY'] ||
    "sb_publishable_gwsMa0bqUMIf2u_opKYieg_s8N47B7E";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});


